# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogAddDevice(object):
    def setupUi(self, DialogAddDevice):
        DialogAddDevice.setObjectName("DialogAddDevice")
        DialogAddDevice.resize(380, 197)
        self.gridLayout = QtWidgets.QGridLayout(DialogAddDevice)
        self.gridLayout.setObjectName("gridLayout")
        self.TypeLineEdit = QtWidgets.QLineEdit(parent=DialogAddDevice)
        self.TypeLineEdit.setObjectName("TypeLineEdit")
        self.gridLayout.addWidget(self.TypeLineEdit, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(parent=DialogAddDevice)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.TasteLineEdit = QtWidgets.QLineEdit(parent=DialogAddDevice)
        self.TasteLineEdit.setObjectName("TasteLineEdit")
        self.gridLayout.addWidget(self.TasteLineEdit, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=DialogAddDevice)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=DialogAddDevice)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.NameLineEdit = QtWidgets.QLineEdit(parent=DialogAddDevice)
        self.NameLineEdit.setObjectName("NameLineEdit")
        self.gridLayout.addWidget(self.NameLineEdit, 0, 1, 1, 2)
        self.RoastingLineEdit = QtWidgets.QLineEdit(parent=DialogAddDevice)
        self.RoastingLineEdit.setObjectName("RoastingLineEdit")
        self.gridLayout.addWidget(self.RoastingLineEdit, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=DialogAddDevice)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.PriceLineEdit = QtWidgets.QLineEdit(parent=DialogAddDevice)
        self.PriceLineEdit.setObjectName("PriceLineEdit")
        self.gridLayout.addWidget(self.PriceLineEdit, 4, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(parent=DialogAddDevice)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=DialogAddDevice)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.SizeLineEdit = QtWidgets.QLineEdit(parent=DialogAddDevice)
        self.SizeLineEdit.setObjectName("SizeLineEdit")
        self.gridLayout.addWidget(self.SizeLineEdit, 5, 1, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogAddDevice)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 3)

        self.retranslateUi(DialogAddDevice)
        self.buttonBox.accepted.connect(DialogAddDevice.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogAddDevice.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogAddDevice)

    def retranslateUi(self, DialogAddDevice):
        _translate = QtCore.QCoreApplication.translate
        DialogAddDevice.setWindowTitle(_translate("DialogAddDevice", "Dialog"))
        self.label_4.setText(_translate("DialogAddDevice", "Type"))
        self.label_2.setText(_translate("DialogAddDevice", "Name"))
        self.label_5.setText(_translate("DialogAddDevice", "Taste"))
        self.label_3.setText(_translate("DialogAddDevice", "Roasting"))
        self.label_6.setText(_translate("DialogAddDevice", "Price"))
        self.label_7.setText(_translate("DialogAddDevice", "Size"))
